[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["tiny_imagenet"]

[project]
name = "tiny_imagenet"
description = "Pre-Training + fine-tuning for tiny-imagenet"

version = "0.0.1"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "Uros Zivanovic", email = "uros.zivanovic@studenti.units.it"},
]
maintainers = [
    {name = "Uros Zivanovic", email = "uros.zivanovic@studenti.units.it"},
]
# Add in any dependancies your experiment has here
dependencies = ["tinyimagenet", "scikit-learn"]

[project.urls]
Repository = "https://github.com/Chromeilion/RoMAE-Experiments"
