[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["elasticc"]

[project]
name = "elasticc"
description = "Classification on the ELAsTiCC dataset."

version = "0.0.1"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "Uros Zivanovic", email = "uros.zivanovic@studenti.units.it"},
]
maintainers = [
    {name = "Uros Zivanovic", email = "uros.zivanovic@studenti.units.it"},
]

dependencies = ["h5py"]

[project.urls]
Repository = "https://github.com/Chromeilion/RoMAE-Experiments"
